[package]
name = "falcon"
version = "0.0.1"
authors = [ "Alex Eubanks <endeavor@rainbowsandpwnies.com>" ]


[profile.dev]
codegen-units = 8
opt-level = 1


[dependencies]
base64 = "0.5"
bincode = "0.8"
bitflags = "0.8"
capstone_rust = { git = "https://github.com/endeav0r/capstone-rust" }
clap = "2.24"
error-chain = "0.10"
goblin = "0.0.9"
log = "0.3"
serde_derive = "1.0.8"
serde_json = "1.0"

serde = {version = "1.0.8", features = ["rc"]}

[lib]
name = "falcon"
path = "lib/lib.rs"


[[bin]]
name = "falcon_bin"
path = "bin/main.rs"